# Generated by Django 5.1.4 on 2024-12-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('League', '0003_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_foundation', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('stadium_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/team_logos/')),
                ('number_of_trophies', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='League.league')),
            ],
        ),
    ]
