# Generated by Django 5.1.4 on 2025-03-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stadium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='city',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
