# Generated by Django 5.1.4 on 2025-02-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default='Liam', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
