# Generated by Django 5.1.4 on 2024-12-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
